name = "SimpleAiboWebAPI"
uuid = "555a2daa-e723-4fb8-a43f-c5b503b4b2ef"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
JSON = "0.21"
HTTP = "0.9"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
