name = "SimpleAiboWebAPI"
uuid = "555a2daa-e723-4fb8-a43f-c5b503b4b2ef"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.3.2"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "0.9"
JSON = "0.21"
julia = "1.3"
DataStructures = "0.18.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
